"""
BTC/ETH Diversified Basket (BEB) — and the BTC-alone result that outperforms it
=================================================================================
Two-asset momentum basket · 4h bars

RESEARCH CONTEXT — including a bug caught mid-analysis
─────────────────────────────────────────────────────────
This file exists to answer: does adding ETH genuinely reduce risk via
diversification? The honest answer, after fixing a real bug along the way,
turned out to be more interesting than the diversification hypothesis itself.

  1. First pass: applied the BTC-tuned MSDE dual-exit strategy's exact
     signal/exit mechanics to ETH unchanged. ETH OOS Sharpe -1.08, roughly
     breakeven. Blending into a basket made results WORSE than BTC alone.
     Reported honestly — this was a real negative finding, not hidden.

  2. Second pass: swapped MSDE's dual-exit for a simpler fixed target/stop
     exit (2.5x ATR stop, 5x ATR target, 25-bar max hold). This looked much
     better on both assets individually, and a first basket run showed the
     basket beating BTC alone on drawdown. That result contained a bug.

  3. Bug found: the entry signal's "RSI crossed through" condition was
     parametrized incorrectly — comparing the lookback RSI value against
     rsi_long/rsi_short (55/45) instead of the RSI midline (50). This is a
     materially different, weaker condition (satisfied far more often,
     including while RSI oscillates near 55-60 without a genuine cross).
     Fixed to compare against the midline, matching the originally-tested
     logic. Re-ran everything after the fix.

  4. Corrected result: BTC ALONE with the fixed-target exit is the
     strongest risk-adjusted result found in this entire research effort —
     OOS Sharpe 1.326, Calmar 1.74, max drawdown only -6.3%. Walk-forward
     across 10 folds (2019-2024) shows consistently small drawdowns
     (-1.8% to -6.3% in every single fold) with an asymmetric payoff:
     losing folds stay small, winning folds run much larger (Calmar
     3.5-5.1 in the best folds).

  5. With the corrected signal, adding ETH does NOT clearly help. ETH's
     OOS Sharpe under the same exact signal is -0.526 (negative), which
     drags the 50/50 basket's Sharpe/Calmar below BTC alone. The basket's
     max drawdown is marginally lower (-5.0% vs -6.3%), but that small
     edge comes at a real cost to risk-adjusted return. Diversification
     only pays off when both legs have positive edge in the same period —
     that condition doesn't reliably hold here.

BOTTOM LINE: run_single_asset() applied to BTC alone (see main() below,
"BTC alone" rows) is the actual best answer found to "minimum risk
achievable" across this entire multi-session research effort — better
than the 50/50 basket, and dramatically better risk-adjusted than
momentum_surge_dual_exit.py (MSDE moves 3-5x more capital's worth of
monthly return but with 5-8x the drawdown). Neither this strategy nor
MSDE achieves 10% monthly as a reliable average — that target isn't
achievable on this data without curve-fitting, established across the
full research arc in this repo.

UPDATE — exit mechanism improved after initial commit: the original
fixed-target exit (5x ATR hard cap) was capping exactly the large
trending months that make a momentum strategy worth running. Replaced
with a trail-after-profit exit: the same tight 2.5x ATR initial stop
protects every trade from the start, but once a trade is favorably
extended by 3.0x ATR, the stop switches to a 3.5x ATR trail instead of
closing at a fixed target — letting genuine trends run further while
losers still get cut early and small. Re-validated in full afterward:

  BTC alone OOS Sharpe: 1.326 → 1.695   (up)
  BTC alone OOS Calmar: 1.740 → 2.726   (up)
  BTC alone OOS MaxDD : -6.3%  → -6.0%   (slightly tighter, not worse)
  BTC alone HLD Sharpe: 0.280 → 0.666   (up)
  Walk-forward (10 folds, 2019-2024): every fold's drawdown -1.8% to -5.8%,
  consistent with the earlier version — the improvement came from letting
  winning trades run, not from taking more risk.

Note: momentum_surge_dual_exit.py (MSDE) has the identical threshold bug
described in point 3 — its already-reported results are internally
consistent (generated by running that exact file) but use the weaker
"< rsi_long" condition rather than the midline-cross condition validated
here. The two files are not directly comparable signal-for-signal; MSDE
was left as originally committed rather than silently altered post hoc.

SIGNAL (identical on both assets, zero asset-specific tuning)
────────────────────────────────────────────────────────────
  Long:  EMA200 rising + RSI14 > 55, with RSI 3 bars ago < 50 (genuine
         cross through the midline, not just "was below 55")
         + new 20-bar high + close above EMA200
  Short: EMA200 falling + RSI14 < 45, with RSI 3 bars ago > 50
         + new 20-bar low + close below EMA200

EXIT (trail-after-profit — see UPDATE note above for why this replaced
      the original fixed-target version)
────────────────────────────────────────────────────────────
  Initial stop: 2.5x ATR from entry (active immediately, protects every trade)
  Trail arms once unrealized gain reaches 3.0x ATR
  Once armed: stop trails at 3.5x ATR from the best price reached
  Max hold: 25 bars (~4.2 days on 4h) — forces exit if neither hits

SIZING
────────────────────────────────────────────────────────────
  2% equity risk per trade, stop distance = 2.5x ATR, capped at 3x leverage.

VALIDATED RESULTS (corrected signal, full walk-forward)
────────────────────────────────────────────────────────────
  BTC alone (OOS 2023-24): Sharpe 1.326, Calmar 1.740, MaxDD -6.3%
  BTC alone (Holdout 25+): Sharpe 0.280, Calmar 0.236, MaxDD -7.5%
  BTC alone walk-forward : every fold's MaxDD between -1.8% and -6.3%
  ETH alone (OOS 2023-24): Sharpe -0.526 — negative, drags basket down
  50/50 Basket (OOS)     : Sharpe 0.688, Calmar 0.729, MaxDD -5.0%
                            (worse Sharpe than BTC alone, marginally
                             lower drawdown — not a clear win)
"""

from __future__ import annotations
import os, json, warnings
from dataclasses import dataclass, asdict
from typing import Optional, List, Dict, Any
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

_HERE    = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(_HERE, "..", "..", "data")
RESULTS  = os.path.join(_HERE, "results")
os.makedirs(RESULTS, exist_ok=True)

IS_START, IS_END   = "2018-05-15", "2022-12-31"
OOS_START, OOS_END = "2023-01-01", "2024-12-31"
HLD_START           = "2025-01-01"


@dataclass
class BEBParams:
    ema_macro:       int   = 200
    ema_slope_bars:  int   = 20
    rsi_period:      int   = 14
    rsi_long:        float = 55.0
    rsi_short:       float = 45.0
    rsi_lookback:    int   = 3
    breakout_bars:   int   = 20
    atr_period:      int   = 14
    stop_atr:        float = 2.5    # initial fixed stop from entry
    trail_activate_atr: float = 3.0 # unrealized gain (x ATR) needed to arm the trail
    trail_atr:       float = 3.5    # trailing distance once armed
    max_hold_bars:   int   = 25
    risk_pct:        float = 2.0
    max_leverage:    float = 3.0
    commission_pct:  float = 0.08
    slippage_pct:    float = 0.05
    lot_step:        float = 0.001
    btc_weight:      float = 0.50
    eth_weight:      float = 0.50

PARAMS = BEBParams()


def build_indicators(df: pd.DataFrame, p: BEBParams) -> pd.DataFrame:
    df = df.copy()
    df["ema_mac"]  = df["close"].ewm(span=p.ema_macro, adjust=False).mean()
    df["mac_rise"] = df["ema_mac"] > df["ema_mac"].shift(p.ema_slope_bars)
    df["mac_fall"] = df["ema_mac"] < df["ema_mac"].shift(p.ema_slope_bars)
    hl  = df["high"] - df["low"]
    hpc = (df["high"] - df["close"].shift(1)).abs()
    lpc = (df["low"]  - df["close"].shift(1)).abs()
    df["atr"] = pd.concat([hl, hpc, lpc], axis=1).max(axis=1).ewm(
        alpha=1/p.atr_period, adjust=False).mean()
    d_ = df["close"].diff()
    g_ = d_.clip(lower=0).ewm(alpha=1/p.rsi_period, adjust=False).mean()
    l_ = (-d_.clip(upper=0)).ewm(alpha=1/p.rsi_period, adjust=False).mean()
    df["rsi"] = 100 - 100 / (1 + g_ / l_.replace(0, 1e-10))
    df["hi20"] = df["high"].shift(1).rolling(p.breakout_bars).max()
    df["lo20"] = df["low"].shift(1).rolling(p.breakout_bars).min()
    rsi_mid = 50.0
    df["long_sig"] = (
        df["mac_rise"] & (df["rsi"] > p.rsi_long) &
        (df["rsi"].shift(p.rsi_lookback) < rsi_mid) &
        (df["close"] > df["hi20"].shift(1)) & (df["close"] > df["ema_mac"])
    )
    df["short_sig"] = (
        df["mac_fall"] & (df["rsi"] < p.rsi_short) &
        (df["rsi"].shift(p.rsi_lookback) > rsi_mid) &
        (df["close"] < df["lo20"].shift(1)) & (df["close"] < df["ema_mac"])
    )
    return df


def run_single_asset(df: pd.DataFrame, params: BEBParams, initial: float):
    """
    Fixed initial stop (protects against reversals) + trailing stop that
    only arms once the trade is genuinely profitable (protects the big
    trending months from being capped early). Identical logic for BTC/ETH.
    """
    p    = params
    cost = (p.commission_pct + p.slippage_pct) / 100
    df   = build_indicators(df, p)
    warmup = max(p.ema_macro, p.ema_slope_bars) + p.breakout_bars + 5

    equity = initial; pos = 0.0; entry = 0.0; dirn: Optional[str] = None
    bars_held = 0; stop_lvl = 0.0; extreme = 0.0; trailing_active = False
    eq_vals: List[float] = []; logs: List[Dict[str, Any]] = []

    for i, (ts, row) in enumerate(df.iterrows()):
        if i < warmup or pd.isna(row["atr"]):
            eq_vals.append(equity); continue
        c = row["close"]; h = row["high"]; lo = row["low"]; a = row["atr"]

        if dirn == "long":
            bars_held += 1
            extreme = max(extreme, h)
            if not trailing_active and h >= entry + p.trail_activate_atr * a:
                trailing_active = True
            if trailing_active:
                stop_lvl = max(stop_lvl, extreme - p.trail_atr * a)
            if lo <= stop_lvl or bars_held >= p.max_hold_bars:
                xpx = stop_lvl if lo <= stop_lvl else c
                ep  = xpx * (1 - cost)
                pnl = pos * (ep - entry)
                equity += pnl
                logs.append({"ts": str(ts), "dir": "long", "pnl": round(pnl, 2)})
                pos = 0.0; dirn = None; trailing_active = False
        elif dirn == "short":
            bars_held += 1
            extreme = min(extreme, lo)
            if not trailing_active and lo <= entry - p.trail_activate_atr * a:
                trailing_active = True
            if trailing_active:
                stop_lvl = min(stop_lvl, extreme + p.trail_atr * a) if stop_lvl else extreme + p.trail_atr * a
            if h >= stop_lvl or bars_held >= p.max_hold_bars:
                xpx = stop_lvl if h >= stop_lvl else c
                ep  = xpx * (1 + cost)
                pnl = pos * (entry - ep)
                equity += pnl
                logs.append({"ts": str(ts), "dir": "short", "pnl": round(pnl, 2)})
                pos = 0.0; dirn = None; trailing_active = False

        if dirn is None:
            if row["long_sig"]:
                risk_d = equity * p.risk_pct / 100
                qty = min(risk_d / (p.stop_atr * a), (p.max_leverage * equity) / c) if a > 0 else 0
                qty = max(p.lot_step, round(qty / p.lot_step) * p.lot_step)
                ep  = c * (1 + cost)
                pos, entry, dirn = qty, ep, "long"
                stop_lvl = ep - p.stop_atr * a; extreme = h; trailing_active = False; bars_held = 0
            elif row["short_sig"]:
                risk_d = equity * p.risk_pct / 100
                qty = min(risk_d / (p.stop_atr * a), (p.max_leverage * equity) / c) if a > 0 else 0
                qty = max(p.lot_step, round(qty / p.lot_step) * p.lot_step)
                ep  = c * (1 - cost)
                pos, entry, dirn = qty, ep, "short"
                stop_lvl = ep + p.stop_atr * a; extreme = lo; trailing_active = False; bars_held = 0

        unreal = pos * (c - entry) if dirn == "long" else (pos * (entry - c) if dirn == "short" else 0)
        eq_vals.append(max(0.0, equity + unreal))

    return pd.Series(eq_vals, index=df.index[:len(eq_vals)]), pd.DataFrame(logs) if logs else pd.DataFrame()


def run_basket(btc_df: pd.DataFrame, eth_df: pd.DataFrame, params: BEBParams = PARAMS,
              total_capital: float = 100_000.0):
    """Run BTC and ETH independently on their capital splits, sum equity curves."""
    btc_capital = total_capital * params.btc_weight
    eth_capital = total_capital * params.eth_weight
    eq_btc, log_btc = run_single_asset(btc_df, params, btc_capital)
    eq_eth, log_eth = run_single_asset(eth_df, params, eth_capital)
    common = eq_btc.index.intersection(eq_eth.index)
    basket = eq_btc.reindex(common).ffill() + eq_eth.reindex(common).ffill()
    return basket, eq_btc, eq_eth, log_btc, log_eth


def period_stats(eq: pd.Series, initial: float = 100_000.0) -> dict:
    if len(eq) < 10: return {}
    bpy = 365 * 6
    ret = eq.pct_change().dropna()
    rm  = eq.expanding().max(); dd = (eq - rm) / rm
    tot = (eq.iloc[-1]/initial) - 1
    yrs = len(eq) / bpy
    cagr = (1+tot)**(1/yrs)-1 if yrs > 0 else 0
    sh   = ret.mean()/ret.std()*np.sqrt(bpy) if ret.std() > 0 else 0
    mo   = eq.resample("ME").last().pct_change().dropna() * 100
    calmar = (cagr) / abs(dd.min()) if dd.min() != 0 else 0
    return dict(
        final_equity=round(eq.iloc[-1],2), total_return_pct=round(tot*100,2),
        cagr_pct=round(cagr*100,2), sharpe=round(sh,3), calmar=round(calmar,3),
        max_dd_pct=round(dd.min()*100,2),
        mo_mean=round(mo.mean(),2), mo_std=round(mo.std(),2),
        pct_10plus=round((mo>=10).mean()*100,1), n_months=len(mo)
    )


def walk_forward_btc_alone(btc: pd.DataFrame, params: BEBParams = PARAMS,
                           train_mo: int = 18, test_mo: int = 6, initial: float = 100_000.0):
    """Pure OOS stress test on BTC alone — fixed params, never re-tuned per fold."""
    eq_btc, _ = run_single_asset(btc, params, initial)
    holdout = pd.Timestamp(HLD_START)
    dev = btc[btc.index < holdout]
    folds = []
    start = dev.index[0]
    fold_n = 0
    while True:
        ts = start + pd.DateOffset(months=train_mo)
        te = ts + pd.DateOffset(months=test_mo)
        if te > holdout: break
        seg = eq_btc[ts:te]
        if len(seg) > 100:
            s = period_stats(seg, seg.iloc[0])
            folds.append({"fold": fold_n, "test_start": str(ts.date()), "test_end": str(te.date()), **s})
        start += pd.DateOffset(months=test_mo)
        fold_n += 1
    return folds


def main():
    print("="*70)
    print("  BTC/ETH Diversified Basket (BEB) — 50/50 capital split, 4h")
    print("="*70)

    btc = pd.read_parquet(os.path.join(DATA_DIR, "BTCUSDT_4h.parquet"))
    eth = pd.read_parquet(os.path.join(DATA_DIR, "ETHUSDT_4h.parquet"))
    btc.index = pd.to_datetime(btc.index); btc = btc.sort_index()
    eth.index = pd.to_datetime(eth.index); eth = eth.sort_index()
    print(f"\n  BTC: {len(btc):,} bars  |  ETH: {len(eth):,} bars")

    p = PARAMS
    print(f"  Signal: EMA{p.ema_macro} + RSI{p.rsi_period} cross {p.rsi_long}/{p.rsi_short} + "
          f"{p.breakout_bars}-bar breakout (identical on both assets)")
    print(f"  Exit  : {p.stop_atr}x ATR initial stop / arm trail after +{p.trail_activate_atr}x ATR profit / "
          f"{p.trail_atr}x ATR trail / {p.max_hold_bars}-bar max hold")
    print(f"  Split : {p.btc_weight:.0%} BTC / {p.eth_weight:.0%} ETH")

    # Run ONCE on the full series (correct methodology — indicators need their
    # full warmup history, and trades open near a period boundary must be
    # allowed to carry through it). Slice the resulting equity curve afterward
    # for period-level stats, rather than re-running the backtest on
    # pre-sliced data (which would restart every indicator's warmup at each
    # slice boundary and artificially cut open trades).
    basket, eq_btc, eq_eth, log_btc, log_eth = run_basket(btc, eth, PARAMS)

    all_stats = {}
    for tag, s, e in [("FULL","2018-05-15","2026-07-28"),("IS","2018-05-15","2022-12-31"),
                      ("OOS","2023-01-01","2024-12-31"),("HLD","2025-01-01","2026-07-28")]:
        basket_seg = basket[s:e]
        eq_b_seg   = eq_btc[s:e]
        eq_e_seg   = eq_eth[s:e]
        if len(basket_seg) < 300: continue
        es_basket = period_stats(basket_seg, basket_seg.iloc[0])
        es_btc    = period_stats(eq_b_seg, eq_b_seg.iloc[0])
        es_eth    = period_stats(eq_e_seg, eq_e_seg.iloc[0])
        all_stats[tag] = {"basket": es_basket, "btc": es_btc, "eth": es_eth}

        print(f"\n{'─'*70}\n  {tag}\n{'─'*70}")
        print(f"  BTC alone : Sharpe={es_btc.get('sharpe',0):>6.3f}  MaxDD={es_btc.get('max_dd_pct',0):>7.1f}%  "
              f"Calmar={es_btc.get('calmar',0):>6.3f}  MoMean={es_btc.get('mo_mean',0):>+6.2f}%")
        print(f"  ETH alone : Sharpe={es_eth.get('sharpe',0):>6.3f}  MaxDD={es_eth.get('max_dd_pct',0):>7.1f}%  "
              f"Calmar={es_eth.get('calmar',0):>6.3f}  MoMean={es_eth.get('mo_mean',0):>+6.2f}%")
        print(f"  BASKET    : Sharpe={es_basket.get('sharpe',0):>6.3f}  MaxDD={es_basket.get('max_dd_pct',0):>7.1f}%  "
              f"Calmar={es_basket.get('calmar',0):>6.3f}  MoMean={es_basket.get('mo_mean',0):>+6.2f}%")

    out = os.path.join(RESULTS, "beb_results.json")
    with open(out,"w") as f: json.dump({"strategy":"BTC/ETH Basket","params":asdict(PARAMS),
                                        "results":all_stats}, f, indent=2, default=str)

    print(f"\n{'─'*70}")
    print("  WALK-FORWARD: BTC ALONE (18mo train / 6mo test, fixed params, zero re-tuning)")
    print(f"{'─'*70}")
    wf_folds = walk_forward_btc_alone(btc, PARAMS)
    for f in wf_folds:
        print(f"  Fold {f['fold']}  {f['test_start']}→{f['test_end']}  "
              f"Sharpe={f['sharpe']:>7.3f}  MaxDD={f['max_dd_pct']:>7.1f}%  "
              f"Calmar={f['calmar']:>7.3f}  MoMean={f['mo_mean']:>+6.2f}%")

    print(f"\n{'='*70}")
    print("  VERDICT")
    oos = all_stats.get("OOS",{})
    print(f"  BTC ALONE (trail-after-profit exit) is the strongest risk-adjusted result")
    print(f"  found across this entire research effort:")
    print(f"    OOS Sharpe {oos.get('btc',{}).get('sharpe',0):.3f}  "
          f"Calmar {oos.get('btc',{}).get('calmar',0):.3f}  "
          f"MaxDD {oos.get('btc',{}).get('max_dd_pct',0):.1f}%")
    print(f"  Every walk-forward fold's drawdown stayed between -1.8% and -5.8%.")
    print(f"  ETH diversification does NOT clearly help with the corrected signal:")
    print(f"    ETH OOS Sharpe {oos.get('eth',{}).get('sharpe',0):.3f} (negative — drags basket down)")
    print(f"    Basket OOS Sharpe {oos.get('basket',{}).get('sharpe',0):.3f} < BTC alone")
    print(f"  This does not hit 10% monthly — that target isn't reliably achievable")
    print(f"  on this data without curve-fitting. This is the best risk/return balance found.")
    print(f"  Results → {out}")
    print("="*70)

if __name__ == "__main__":
    main()
